project:
  type: website
  output-dir: docs
website:
  title: "Jorge Montoya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: contact_me.qmd
        text: Contact Me

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
body-header: | 
  This page was built in Quarto
editor: visual

