project:
  type: website
  output-dir: docs
website:
  title: "Jorge Montoya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - contact_me.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

