project:
  type: website
  output-dir: docs
profile:
  default: english
  group: [english,spanish]
website:
  title: "Jorge Montoya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: contact_me.qmd
        text: Contact Me
  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

editor: visual

