---
title: "About Me"
lang: es
---

## Who I am

An **analytics professional** with **5+ years** of experience in **analytics, product design/development, and business strategy**

## **My Journey**

I am a first generation Peruvian immigrant who is passionate for improving the lives of people and bringing communities together. In the beginning of my career, I started working in the private wealth industry to help others achieve their investing goals by managing their investment data and presenting insights that would help them make informed decisions for their portfolios and finances. This interest in storytelling through data with purpose led me to pursue a Master's degree in Data and Analytics from Northeastern. This educational experience broadened my horizons in how storytelling with data and the use of analytics can drive meaningful impact and organizational growth.

With this new perspective, I moved onto the healthcare industry in order to continue my pursuit of applying data, analytics and storytelling to drive and improve the lives of people. I started working at Premier where I am focused in formulating, designing and developing scalable solutions that aim to drive meaningful change and positive impact to business and communities that are most affected. I have led and contributed on multiple solutions  (i.e. application, dashboards, process improvements) through efforts in product design, product development, proof of concept building, evidence of business value generation and translating prototypes into production-ready solutions.

🔗 [**View My Projects**](projects.qmd) \| 🔗 [**Read about my experience**](blog.qmd)

## Values and How They Impact My Work

-   Inclusion & Diversity of Thought

    Embracing diverse perspectives to \*\*foster innovation\*\* and drive \*\*collaboration\*\*.

-   Impact-Driven & Mission-Aligned

    Passionate about \*\*creating meaningful solutions\*\* that align with \*\*vision & long-term goals\*\*.

-   Accountability & Ownership

    Taking responsibility for \*\*outcomes\*\* and delivering \*\*results with integrity\*\*.

-   Performance & Efficiency

    Continuously \*\*optimizing processes\*\* and driving \*\*operational excellence\*\*.

-   Solution-Oriented Mindset

    Every challenge has a \*\*solution\*\*—I believe in \*\*problem-solving through innovation\*\*.

-   Knowledge Sharing & Collaboration

    Empowering others by \*\*sharing insights\*\* and fostering a \*\*culture of learning\*\*.

-   Creative & Strategic Thinking

    Challenging the \*\*status quo\*\* to develop \*\*innovative solutions\*\*.

-   Community-Driven & Global Perspective

    Thinking \*\*globally\*\* while making a \*\*local impact\*\* through meaningful contributions.

## Key Expertise Areas

-   Project management

-   Design-thinking

-   Market research and analysis

-   Prototyping

-   Business case generation

-   Data analysis

-   Machine learning modelling

-   Systems design

-   Process improvement

## Skills

```{=html}
<iframe src="figures/interactive_skills_chart.html" width="100%" height="600px"></iframe>
```

## Fun interests:

-   Cooking

-   Hiking outdoors

-   Sports (big Liverpool FC fan and all Miami-based teams)

-   Volunteering

-   Books

    -   El secreto del bambu

    -   Crucial conversations
